### PR TITLE
feat(kube): add a FilteredList() filters out null values in array

### PR DESCRIPTION
**Pull request by jaredallard**
**What this PR does**: This introduces `ok.FilteredList()` to filter out null values.

### CODE REVIEW

**Review by AlexisJasso — CHANGES_REQUESTED** [review]
I'd suggest making this as a new function.  I'm not sure how to test that this don't have unintended side effects.

**Comment by jaredallard** [comment]
@AlexisJasso I figured as much, will do so!

**Comment by jpanderson-outreach** [comment]
This is also sort of an existing thing? `std.prune(a thing with null or empty stuff)`

```
{
  a: { b: 'banana', c: null, d: ''},
  ary: [null, 1, 2],
  obj_result: std.prune($.a),
  ary_result: std.prune($.ary),
}
```

```
{
  "a": {
    "b": "banana",
    "c": null,
    "d": ""
  },
  "ary": [
    null,
    1,
    2
  ],
  "ary_result": [
    1,
    2
  ],
  "obj_result": {
    "b": "banana",
    "d": ""
  }
}
```

**Comment by jaredallard** [comment]
@jpanderson-outreach My concern with `std.prune`, and I shouldve called this out, is that it states:

> Recursively remove all "empty" members of a. "Empty" is defined as zero length `arrays`, zero length `objects`, or `null` values. The argument a may have any type.

I was worried that would have unintended side effects

**Comment by jpanderson-outreach** [comment]
@jaredallard fair enough, that may be undesirable.

```
local amazing = {
  foo: {
    bar: {
      baz: null,
      amazingTime: '',
      whatAPlace: 3,
    },
  },
};

{
  blah: std.prune(amazing)
}

# Results in
{
   "blah": {
      "foo": {
         "bar": {
            "amazingTime": "",
            "whatAPlace": 3
         }
      }
   }
}
```

**Review by epinault — APPROVED** [review]
LGTM as far I can tell.

**Review by AlexisJasso — APPROVED** [review]
Yep.  This creates two new functions and shouldn't impact any existing manifests.  Go for it.

**Pull request merged**
