### PR TITLE
Add environment to bentos helper

### PR DESCRIPTION
**Pull request by AlexisJasso**
See subject.  Based on feedback from the `noggin-kafka` project.  Trying to keep this information generic, but this seems like it could be a useful add.

### CODE REVIEW

**Comment by frightenedmonkey** [comment]
@jpanderson-outreach I think that might be a fairly big PITA to dig out all the things that use env vs environrment. But, you know.

**Comment by AlexisJasso** [comment]
> not loving that we have `env` for the per-cluster and `environment` for the bentos. Can we pick one and standardize on that in here?

Good call.  Done.

**Comment by jpanderson-outreach** [comment]
@frightenedmonkey afaik, nothing old is using these so I'd rather not give people the option going forward. If someone wants `env` and not `environment`, they can set their own jsonnet key/variable.

**Comment by AlexisJasso** [comment]
> @jpanderson-outreach I think that might be a fairly big PITA to dig out all the things that use env vs environrment. But, you know.

We can always map `env=bento.environment` if it's necessary to have it the other way.  But this way the library is consistent.

**Pull request merged**
